# Don't change this
theme: jekyll-theme-primer

# AMWA ID
amwa_id: IS-05

# GitHub project
baseurl: /nmos-device-connection-management

# Which relase or branch appears in header links and on the home page
default_tree: tags/v1.1 # alternatively e.g. branches/v1.0.x

# Regex patterns of tags (releases) and branches to show
show_tags: v[0-9]*\.[0-9]*
show_branches: v[0-9]*\.[0-9]*
